#!/bin/bash

echo "🔄 EXTENSION RELOAD INSTRUCTIONS"
echo ""
echo "To reload your extension and clear all context errors:"
echo ""
echo "1. Open Chrome: chrome://extensions/"
echo "2. Find 'The Great Suspender (NoTrack)'"
echo "3. Click the RELOAD button (🔄)"
echo "4. Close all suspended tabs"
echo "5. Test the extension"
echo ""
echo "OR use the keyboard shortcut:"
echo "1. Press Ctrl+Shift+R on the extensions page"
echo "2. This will reload all extensions"
echo ""
echo "📊 After reload, the extension should work with:"
echo "   ✅ No context invalidation errors"
echo "   ✅ Clean service worker startup"
echo "   ✅ Working popup and options"
echo "   ✅ All 18 themes still available"
echo ""
echo "🎯 If you still see context errors:"
echo "   1. Run: ./fix21_final_context_fix.sh"
echo "   2. Use the minimal content script (already set)"
echo "   3. Reload extension again"
